[package]
name = "inputkey-language-pack-french"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
name = "InputKeyLanguageFrench"
crate-type = ["cdylib"]

[dependencies]
inputkey-language-pack-native-abi = { path = "../../../Implementations/LanguagePackNativeABI" }
inputkey-language-pack-abi = { path = "../../LanguagePackABI" }
inputkey-language-french = { path = "../../../Implementations/Languages/French" }
