[package]
name = "inputkey-cabi"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
inputkey-boundary = { path = "../../Boundary" }
inputkey-core-abstractions = { path = "../../CoreAbstractions" }
inputkey-operators = { path = "../../Operators" }
inputkey-runtime = { path = "../Runtime" }
