[package]
name = "inputkey-cabi"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
inputkey-boundary = { path = "../../Boundary" }
inputkey-english-bloom = { path = "../../Implementations/EnglishBloom" }
inputkey-operators = { path = "../../Operators" }
