[package]
name = "inputkey-windows-app"
version.workspace = true
edition.workspace = true
license.workspace = true
[[bin]]
name = "InputKey"
path = "src/main.rs"
[dependencies]
inputkey-windows-hook = { path = "../../Implementations/WindowsHook" }
inputkey-boundary = { path = "../../Boundary" }
inputkey-operators = { path = "../../Operators" }
inputkey-english-bloom = { path = "../../Implementations/EnglishBloom" }
inputkey-core-abstractions = { path = "../../CoreAbstractions" }
