[package]
name = "inputkey-language-pack-swedish"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
name = "InputKeyLanguageSwedish"
crate-type = ["cdylib"]

[dependencies]
inputkey-language-pack-native-abi = { path = "../../../Implementations/LanguagePackNativeABI" }
inputkey-language-pack-abi = { path = "../../LanguagePackABI" }
inputkey-language-germanic = { path = "../../../Implementations/Languages/Germanic" }
