[package]
name = "inputkey-windows-control"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
inputkey-core-abstractions = { path = "../../CoreAbstractions" }
inputkey-windows-settings = { path = "../WindowsSettings" }

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.59", features = [
    "Win32_Foundation",
    "Win32_Graphics_Gdi",
    "Win32_Security",
    "Win32_System_LibraryLoader",
    "Win32_UI_Input_KeyboardAndMouse",
    "Win32_UI_Shell",
    "Win32_UI_WindowsAndMessaging",
] }
